### ISSUE TITLE
Submission Form+Automation

### ISSUE THREAD

**Issue by andrew8404** [FluentCRM/fluent-crm#1]
Hi,I'm not sure it's the right place to report a issue here,I started to test fluentcrm a few days ago,first thing is setting up a submission form,and enable double opt-in email conformation,the vistiors submit their emails throught the form and captured in fluentcrm contacts,showing submisson status  "pending" before the vistiors click the confirmation button in email,once they confirm the the submission,the stauts will change to "subscribed",everything is good so far.But after setting up an automation for sending a marketing email to the subscribers whos status are"subscribed",the form will ingore the pending status, subscribers don't need to click confirmation even they can get the double opt-in confirmation email.their submission status are"subscribed" already after they submit the email through that form.

**Comment by techjewel** [comment]
If a contact is already in your database and in subscribed status then it will be that way. In Fluent Forms, You can use double optin so it will push the data only if user click the confirmation link.
