### ISSUE TITLE
Apply List action is not working.

### ISSUE THREAD

**Issue by routesdevsupport** [FluentCRM/fluent-crm#2]
Hello,

The action "Apply List" is not working in latest version 1.1.80. It was working in version 1.1.5. I have checked the plugin code and see code for add user to the particular list is no more available in the latest version.

You can see the previous plugin code for add user to the list here: https://github.com/FluentCRM/fluent-crm/blob/a4018eb71b2b68f261d4cede5f54e217138cae55/app/Services/Funnel/Actions/ApplyListAction.php#L58

This is no more available in the latest version.

**Comment by techjewel** [comment]
We have fixed this long ago.
