### ISSUE TITLE
Stop using the development autoloader.

### ISSUE THREAD

**Issue by calvinalkan** [FluentCRM/fluent-crm#27]
Currently, FluentCRM comes with the composer autoloader that searches files and directories at runtime.

This will cause significant performance hits on sites with many custom autoloader classes. 

FluentCRM's composer autoloader must only handle it's only classes. 

For that, you need to run:

```shell
composer dump-autoload --classmap-authoritative
```

during the release process. 

> If you need to update the autoloader because of new classes in a classmap package for example, you can use dump-autoload to do that without having to go through an install or update.
> 
> Additionally, it can dump an optimized autoloader that converts PSR-0/4 packages into classmap ones for performance reasons. In large applications with many classes, the autoloader can take up a substantial portion of every request's time. Using classmaps for everything is less convenient in development, but using this option you can still use PSR-0/4 for convenience and classmaps for performance.

https://getcomposer.org/doc/03-cli.md#dump-autoload-dumpautoload

**Comment by techjewel** [comment]
Noted and will be implemented to all the plugins
