### ISSUE TITLE
Sugestions

### ISSUE THREAD

**Issue by Ricardo-Miguel-Caldeira** [FluentCRM/fluent-crm#3]
Sorry if I'm posting this in the wrong place but could find it anywhere...

I have a few suggestions that probably can be implemented quickly and bring more flexibility to FluentCMS.
I'm a frequent user of other CRM systems and I've noticed almost immediatly a few important things: 

- Email a subscriber directly (One2One emails). Maybe using the templates and logging the sent email also...
- In the Contact profile, in the field "Prefix" there are also some default values Mr., Mrs.. How can we change this? Such a small thing like this has a negative impact to the user...
- Add items on the fly in the multy-select list (custom field) is not possible.
- Strange chars appear when using accents in the name of the custom fields (áàãõéêç). Also no ability to change the "fieldName". Conditional fields is also a must but that's why there is a pro version. My suggestion is between fields themselves (District, State, Province). Maybe put some time on custom fields to setup max lenght, validation rules, Etc.

Please don't get me wrong. I've been trying to use FluentCRM and learn about it before I'm putting any money on it... Some of this small things have a huge impact to the user experience. Just keep the good work and keep improving.

**Comment by techjewel** [comment]
First of all sorry for the late reply. We missed the github issues and from now, We will maintain this repo as well. 

1. You can send an email from the contact profile also it you can see all the outgoing emails from FluentCRM to that contact
2. To add or replaces name prefixed you can use this hook:

```php
add_filter('fluentcrm_contact_name_prefixes', function($prefixes) {
     $prefixes = [
             'Mr',
            'Mrs',
            'Ms',
            'Dr.
     ];

     return $prefixes;
}
```

3. For now, You have to setup `Multiple Select choice` field type on custom fields but I am afraid adding new from profile tab is not available yet.
4. I hope the strange chars issue has been resolved long ago

Thank you for using Fluent CRM :)
