### ISSUE TITLE
Open Rates (I know they're always flawed but this is different)

### ISSUE THREAD

**Issue by kevinhoodme** [FluentCRM/fluent-crm#5]
Hey there,

I'm well aware open rates are flawed but I see something happening with FluentCRM that I haven't seen with any other email marketing service (and I've tried many such as: aweber, convertkit, mailchimp, kartra, activecampaign, mailerlite, etc...)

FluentCRM seems to be the only one that will automatically mark a random percentage of subscribers as having opened the email immediately after it is sent.

Here's a video:
https://www.loom.com/share/c6e08909aacf47ee89a85edcd7bcbf39

**Comment by techjewel** [comment]
Hello @kevinhoodme 
Basically, open rate is pixel-based so it's not perfect. Some email clients load the image even you open the email and in that case, the email marked as opened. 

We will revisit again and check if we can improve it :)
