### ISSUE TITLE
Error in API documentation: Get contact by user_id

### ISSUE THREAD

**Issue by karlemilnikka** [FluentCRM/fluent-crm#6]
There is an error in the API documentation in the wiki and on the FluentCRM Docs website. 

- https://github.com/FluentCRM/fluent-crm/wiki/PHP-API 
- https://fluentcrm.com/docs/contact-php-api/

To get contact by user_id, getContactByUserId( $user_id ) should be used, not getContact($user_id).

Best regards
Karl Emil Nikka

**Comment by techjewel** [comment]
Thanks for reporting. We have fixed it :)
